services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"  
    volumes:
      - .:/tron_backend  
    networks:
      - tron-backend
    env_file:
      - .env
    depends_on:
      - db
    command: >
      sh -c "
      alembic upgrade head &&
      uvicorn --factory src.main:setup_app --host 0.0.0.0 --port 5000
      "

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test_db
    ports:
      - "5434:5432"
    networks:
      - tron-backend
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  tron-backend:
    driver: bridge

volumes:
  postgres_data:
