"""0001

Revision ID: 29a3ad7dea48
Revises:
Create Date: 2024-12-26 19:45:02.927186

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "29a3ad7dea48"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "wallets",
        sa.Column("address", sa.String(length=255), nullable=False),
        sa.Column("bandwidth", sa.Integer(), nullable=False),
        sa.Column("energy", sa.Integer(), nullable=False),
        sa.Column("balance", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("address"),
    )
    op.create_table(
        "wallet_requests",
        sa.Column("wallet_id", sa.UUID(), nullable=False),
        sa.Column("request_time", sa.DateTime(), nullable=False),
        sa.Column("response_time", sa.DateTime(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "success",
                "failure",
                "processing",
                name="wallet_request_status",
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["wallet_id"],
            ["wallets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("wallet_requests")
    op.drop_table("wallets")
    # ### end Alembic commands ###
